### ISSUE TITLE
TDBM 3.3 : infinite loop if table not exists 

### ISSUE THREAD

**Issue by vaidiep** [thecodingmachine/database.tdbm#90]
In a LessFilter, if you pass a table name that doesn't exists, the method getListByFilter leads to an infinite loop.

I think that you must test before if the table exists and thus, throw an exception if not.

**Comment by vaidiep** [comment]
``` php
public function getUnpaidObjects() {
        $filters = [];
        $filters[] = new EqualFilter("objects", "status_id", SalleBean::STATUT_SUSPENDU_IMPAYEE);
        $filters[] = new LessFilter("salles", "date_fin_abo", date("Y-m-d", time()));
        return $this->getListByFilter($filters);
}
```

I have written "salle" instead of "salles

**Comment by moufmouf** [comment]
Is it really an infinite loop?
For very complex object models, TDBM will need to go through all the relationships, which can take quite some time. Most of the time, it will go over the PHP execution time limit. Yet, this is not a real infinite loop.

Also, this is fixed in TDBM 4 (TDBM 4 is way faster and does not reach the execution time limit). I'd rather avoid spending too much time fixing problems that are only related to error reporting on an old version of TDBM (I would gladly correct this on TDBM 4 if this is an issue, though).
